

spring.application.name=Sajili
#server port
server.port=8080

server.address=0.0.0.0
#//JPAHibernate Configuration
spring.jpa.hibernate.ddl-auto= update
#show sql queries in logs
spring.jpa.show-sql= true
<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://localhost:5432/sajilidb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
=======
spring.datasource.url=jdbc:h2:mem:sajilidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Allow Hibernate to create the 'Profile' table automatically
spring.jpa.hibernate.ddl-auto=update

# Enable H2 Console (Optional: view data at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
>>>>>>> 03cfdcc46b34b0c5e4d17c3ca196dedeab85b2b0



logging.level.org.springframework.security=DEBUG



